TeamPophory/pophory-android

app/build.gradle.kts
gradle/libs.versions.toml

[feature/add-dependency] dot-indicator 의존성 추가

---

.github/ISSUE_TEMPLATE/pophory-issue-template.md 

Update Issue template

---

.github/workflows/develop_PR_builder.yml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt

- Sentry 프로젝트 설정 완료했습니다. 노션에 있는 local.properties 설정 페이지 보고 본인 프로젝트의 local.properties 바꿔주시면 감사하겠습니다.

:chart_with_upwards_trend: Add sentry configuration

---

gradle/libs.versions.toml

- Compose compiler 1.4.8 업데이트 가능해서 코틀린 버전도 올림

:wrench: Update library versions

---

app/build.gradle.kts
app/src/debug/AndroidManifest.xml
app/src/debug/java/com/teampophory/pophory/FlipperInitializer.kt
app/src/main/java/com/teampophory/pophory/App.kt
app/src/release/java/FlipperInitializer.kt
gradle/libs.versions.toml

- close #28 
- [Flipper LINK](https://fbflipper.com/docs/getting-started/android-native/)

[feature/flipper-config] Flipper 설정하기

---

app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

Add Crashlytics dependencies

---

app/src/main/java/com/teampophory/pophory/config/initializer/AdInitializer.kt
app/src/main/java/com/teampophory/pophory/config/initializer/CrashlyticsInitializer.kt
app/src/main/java/com/teampophory/pophory/config/initializer/TimberInitializer.kt
build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/CommonConfigs.kt

[feature/timber-config] Timber 로거 설정

---

app/src/main/res/color/selc_bottom_nav_item.xml
app/src/main/res/layout/activity_home.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/themes.xml

[feature/design-system] Color Design System 설정

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/teampophory/pophory/design/Color.kt
app/src/main/java/com/teampophory/pophory/design/Theme.kt
app/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt
app/src/main/java/com/teampophory/pophory/feature/setting/SettingScreen.kt
app/src/main/java/com/teampophory/pophory/feature/setting/component/LogoutDialog.kt
app/src/main/java/com/teampophory/pophory/feature/setting/component/SettingItem.kt
app/src/main/java/com/teampophory/pophory/feature/setting/component/SettingScreen.kt
app/src/main/java/com/teampophory/pophory/feature/setting/component/WithdrawDialog.kt
app/src/main/res/drawable/ic_chevron_left.xml
app/src/main/res/drawable/ic_chevron_right.xml
app/src/main/res/drawable/ic_close.xml
build-logic/convention/build.gradle.kts
build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/ComposePlugin.kt
core/common/build.gradle.kts
core/common/src/main/java/com/teampophory/pophory/common/compose/Border.kt
core/common/src/main/java/com/teampophory/pophory/common/compose/DefaultPreview.kt
gradle/libs.versions.toml

[feature/setting] 설정화면 제작

---

app/src/main/java/com/teampophory/pophory/feature/signup/SignUpDialogFragment.kt

[feat/dialogFragment] : requestFeature 삭제

---

app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
core/common/build.gradle.kts
core/common/src/main/java/com/teampophory/pophory/common/activity/ActivityExt.kt
core/common/src/main/java/com/teampophory/pophory/common/fragment/FragmentExt.kt
core/common/src/main/java/com/teampophory/pophory/common/view/LoadingProgressIndicator.kt
core/common/src/main/res/layout/fragment_progress_dialog.xml

close #93 
사용법은 Activity or Fragment에서 showLoading(), hideLoading() 을 쓰면 가능! 어디서든 편하게 사용하십쇼
https://github.com/TeamPophory/pophory-android/assets/93872496/97d0f7df-26b9-4d93-9c6e-f69959713e62

[feat/indicator]: Indicator 추가

---

app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
app/src/main/java/com/teampophory/pophory/network/model/NicknameResponse.kt
app/src/main/java/com/teampophory/pophory/network/retrofit/signup/RetrofitSignUpNetwork.kt

- close #104 
[Screen_recording_20230707_224833.webm](https://github.com/TeamPophory/pophory-android/assets/52442547/0e4caadc-0e42-4fd3-a27a-579aa2182f60)
닉네임 중복 체크 api 연결

[feat/nickname_check]: add network 닉네임 중복체크

---

app/src/main/java/com/teampophory/pophory/albumsort/AlbumSortBottomSheet.kt
app/src/main/java/com/teampophory/pophory/data/network/model/auth/AuthResponse.kt
app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageDisplayItem.kt
app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
app/src/main/java/com/teampophory/pophory/feature/home/mypage/adapter/MyPageAdapter.kt
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoViewModel.kt
app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
app/src/main/java/com/teampophory/pophory/feature/signup/SignUpDialogFragment.kt
app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
app/src/main/java/com/teampophory/pophory/network/model/MyPageResponse.kt
app/src/main/res/layout/bottom_sheet_album_sort.xml
app/src/main/res/layout/fragment_album_delete_dialog.xml
core/common/src/main/java/com/teampophory/pophory/common/context/ContextExt.kt

- 피드선택시 사진 상세뷰 이동
- 삭제 다이얼로그 변경
- check 버튼 변경

[Feature/fix qa] QA 수정사항

---

app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt

앨범 리스트 내부에서 사진 업로드시 크래시 발생 대응 및 홈화면 이동로직 추가

[feature/qa album detail]: 앨범 리스트 내부에서 사진 업로드

---

app/proguard-rules.pro

[feature/proguard] Add proguard rules for minify

---

app/src/main/java/com/teampophory/pophory/config/di/AuthModule.kt
app/src/main/java/com/teampophory/pophory/config/di/MyPageModule.kt
app/src/main/java/com/teampophory/pophory/config/di/NetModule.kt
app/src/main/java/com/teampophory/pophory/config/di/PhotoModule.kt
app/src/main/java/com/teampophory/pophory/config/di/StoreModule.kt
app/src/main/java/com/teampophory/pophory/config/di/qualifier/Auth.kt
app/src/main/java/com/teampophory/pophory/data/network/authenticator/PophoryAuthenticator.kt
app/src/main/java/com/teampophory/pophory/data/network/model/auth/TokenResponse.kt
app/src/main/java/com/teampophory/pophory/data/network/service/RefreshApi.kt
app/src/main/java/com/teampophory/pophory/domain/ConfigureMeUseCase.kt
app/src/main/java/com/teampophory/pophory/feature/HomeViewModel.kt

[feature/authenticator] 401 Authenticator 처리

---

app/src/main/java/com/teampophory/pophory/App.kt

- close #142 
가로모드 관련 테스트를 완료하였습니다.

[feature/rotate_block]: add rotate block

---

app/src/main/java/com/teampophory/pophory/config/ad/AdmobNativeAdService.kt
app/src/main/java/com/teampophory/pophory/config/ad/AdmobRewardedAdService.kt
app/src/main/java/com/teampophory/pophory/feature/sample/AdmobSampleActivity.kt

[feat/admob_reward]: reward video service 추가

---

app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
core/common/src/main/java/com/teampophory/pophory/common/image/UriExt.kt

[Fix/image_size]: image_size get 로직 수정

---

app/src/main/java/com/teampophory/pophory/config/di/NetModule.kt
app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
app/src/main/java/com/teampophory/pophory/data/repository/photo/DefaultPhotoRepository.kt
app/src/main/java/com/teampophory/pophory/domain/repository/photo/PhotoRepository.kt
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoViewModel.kt
core/common/src/main/java/com/teampophory/pophory/common/image/BitampRequestBody.kt
core/common/src/main/java/com/teampophory/pophory/common/image/ContentUriReqeustBody.kt
core/common/src/main/java/com/teampophory/pophory/common/image/UriExt.kt

[feature/limit-photo-size-format] 사진 용량 3MB, 포맷 JPEG 제한

---

app/build.gradle.kts
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
gradle/libs.versions.toml

[feature/image-rotate-issue-fix] 갤러리에서 가져온 이미지가 회전되어 보이는 이슈 해소

---

app/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt

[feature/change_url]: 서비스 이용약관 및 개인정보 처리방침 url change

---

app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListViewModel.kt
app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
app/src/main/res/drawable/bg_round_100dp_black.xml
app/src/main/res/layout/activity_add_photo.xml
app/src/main/res/layout/activity_album_list.xml
app/src/main/res/values/themes.xml
app/src/main/res/values/type.xml

[feature/add_photo]: add_photo view 변경

---

app/build.gradle.kts
app/src/main/java/com/teampophory/pophory/feature/setting/SettingActivity.kt
app/src/main/java/com/teampophory/pophory/feature/setting/SettingScreen.kt
app/src/main/java/com/teampophory/pophory/feature/setting/TeamScreen.kt
app/src/main/java/com/teampophory/pophory/feature/setting/TermScreen.kt
build.gradle.kts
gradle/libs.versions.toml

[feature/setting-screen] 설정화면 수정 반영

---

app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
app/src/main/res/layout/fragment_store.xml

- close #205 
[Screen_recording_20230720_160536.webm](https://github.com/TeamPophory/pophory-android/assets/52442547/016a469d-5d24-4170-a04d-5214e7c954b8)

[Fix/share-check] Intent 이후 체크 표시 해제 이슈 해결

---

app/src/main/res/layout/dialog_common_one_button.xml
app/src/main/res/layout/fragment_mypage.xml
app/src/main/res/values/strings.xml

[Fix/my page error]: my page 라이팅 및 색상 수정

---

app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt

[fix/delete_error]: 사진 삭제 오류 수정

---

app/src/main/java/com/teampophory/pophory/config/di/PreferencesModule.kt

[Link](https://pophory.sentry.io/issues/4332426249/?project=4505431713513472&query=is%3Aunresolved+release.version%3A1.1.2&referrer=issue-stream&statsPeriod=14d&stream_index=2)
- EncryptedSharedPreference 생성 시 tink error 때문에 1.1.0-alpha06 버전을 사용하고 있었는데...이외에도 잔존 이슈가 남아있는 것 같습니다. 그래서 workaround로 keystore 초기화 로직을 집어넣어서 크래시 오류를 해결하고자 합니다.
- 특정 기기에서만 재현되는 것이어서...이후에 Firebase Test Lab이나 Device Farm 활용해서 광범위한 실기기 테스트 들어가면 좋을 것 같습니다. (지금 이 PR에선 말고)

Fix error when app preferences create

---

app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
app/src/main/java/com/teampophory/pophory/feature/home/HomeViewModel.kt
app/src/main/java/com/teampophory/pophory/feature/home/HomeViewState.kt
app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt

- close #247 
Event 는 SharedFlow로 처리하였습니다.

[feature/home_viewmodel_refactor]:HomeViewModel refactoring 작업

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoActivity.kt
app/src/main/java/com/teampophory/pophory/feature/home/photo/AddPhotoViewModel.kt
app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
app/src/main/java/com/teampophory/pophory/feature/home/store/StoreViewModel.kt
core/common/src/main/java/com/teampophory/pophory/common/intent/ExtraExt.kt

- close #286 
- Album Id 가 필요한 이슈로 AddPhotoActivity로 바로 이동하지 않고 HomeActivity에서 intent확인 후 startActivity하는 형식으로 처리했습니다.

[Feature/photo share]: 갤러리에서 공유하기시 사진 공유 가능하도록 처리

---

README.md
gradle/libs.versions.toml

Bump Kotlin, Compose compiler, lifecycle version

---

app/build.gradle.kts
app/proguard-rules.pro
app/src/main/java/com/teampophory/pophory/feature/home/HomeViewModel.kt
build.gradle.kts
core/network/build.gradle.kts
data/ad/build.gradle.kts
data/auth/build.gradle.kts
data/auth/src/main/java/com/teampophory/pophory/data/auth/repository/DefaultAuthRepository.kt

- sentry 제거
- retrofit proguard 수정

[feature/fix_build] sentry 제거 및 retrofit proguard 수정
